'use client'

// import type { Metadata } from 'next'
// import { Inter } from "next/font/google";
import './globals.css'
import { RecoilRoot } from 'recoil'

// export const metadata: Metadata = {
//   title: 'leetcode',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <RecoilRoot>{children}</RecoilRoot>
      </body>
    </html>
  )
}
